Repository Automattic/vip-search-replace, pull requests merged in 2021-02, with the labels that each got.

#11 fix: hanging output stream
  lib/index.js
Labels: semver-patch

#12 fix: Attach stream listeners prior to starting flow
  lib/index.js
Labels: [Status] Needs Review, semver-patch

#13 fix: Don't block at all, just return output stream
  lib/index.js
Labels: [Status] Needs Review, semver-patch

#14 Refactor install lib and script -- download binary to package dir
  .gitignore
  LICENSE
  __tests__/lib/index.test.js
  bin/go-search-replace
  bin/install-binary.js
  lib/index.js
  lib/install-go-binary.js
  package-lock.json
  package.json
Labels: bug, enhancement, semver-patch

#15 Fall back to a temp dir when unable to access package dir
  __tests__/lib/index.test.js
  bin/install-binary.js
  lib/index.js
  lib/install-go-binary.js
Labels: [Status] Needs Review, bug, semver-patch

#16 fix: Explicitly close file descriptor after install
  lib/install-go-binary.js
Labels: [Status] Needs Review, semver-patch

#17 fix: Correct GOARCH. arm64, not arm
  __tests__/lib/index.test.js
  lib/install-go-binary.js
Labels: [Status] Needs Review, semver-patch

#18 fix: Correctly reference the arm64 arch
  __tests__/lib/index.test.js
  lib/install-go-binary.js
Labels: [Status] Needs Review, semver-patch

#19 build: Add allowed list of os & cpu
  __tests__/lib/index.test.js
  lib/install-go-binary.js
  package.json
Labels: [Status] Needs Review, semver-patch
